activeprospect/leadconduit-integration-trustedform

package.json
spec/claim_spec.coffee
src/claim.coffee

@alexkwolfe: I don't recall if using `toString()` like that is ok, or if there's a better way.

fixed to populate values for email and phone ('rich' String types)

---

spec/claim_spec.coffee
src/claim.coffee

Two variables renamed, the parameter sent to TF fixed, and a little git flailing. :confused:

Scan support

---

.travis.yml
spec/claim_spec.coffee
src/claim.coffee

@alexkwolfe take a look, and also let me know if you want this deployed now, or held until Thursday.

removed 'event_duration' from calculation, fixes #24

---

spec/claim_spec.coffee
src/claim.coffee

update hosted_url, add test

---

CHANGELOG.md
package.json
spec/claim_spec.coffee
src/claim.coffee

fix to use single cert URL when multiple provided

---

package.json
spec/claim_spec.coffee
src/claim.coffee

fix tests to use the right types

---

.npmrc
CHANGELOG.md
spec/claim_spec.coffee
src/claim.coffee

Capture duration

---

CHANGELOG.md
lib/claim.js
test/claim_spec.js

Add vendor variable

---

lib/claim.js
test/claim_spec.js

closes #33.
The anchor might be unnecessary.

Update URL validation

---

CHANGELOG.md
lib/claim.js
test/claim_spec.js

For more info, see the third item on the TP card linked below.
https://activeprospect.tpondemand.com/entity/2570-trustedform-improvements

Send message on 410 errors

---

CHANGELOG.md
lib/claim.js
lib/helpers.js
package.json
test/claim_spec.js
test/helper_spec.js

Per [TP #8409](https://activeprospect.tpondemand.com/entity/8409-trustedform-append-fingerprinting), add append fields for TF's fingerprint results.

Add fingerprints

---

CHANGELOG.md
lib/claim.js
lib/helpers.js
package.json
test/claim_spec.js

https://app.clubhouse.io/active-prospect/story/5385/use-new-tf-node-library-in-existing-integration

use the TF api client package

---

CHANGELOG.md
lib/claim.js
package.json
test/claim_spec.js

Story details: https://app.clubhouse.io/active-prospect/story/8667

Append the token to the TF integration response

---

CHANGELOG.md
lib/claim.js
test/claim_spec.js

Story details: https://app.clubhouse.io/active-prospect/story/9421

Correct the appended token data in TrustedForm

---

.github/workflows/test.yml
.gitignore
docs/outbound.claim.md
docs/outbound.data_service.md
index.js
lib/claim.js
lib/data_service.js
lib/helpers.js
lib/ui/index.js
lib/ui/public/app/config/Config.vue
lib/ui/public/app/config/PageOne.vue
lib/ui/public/app/config/PageThree.vue
lib/ui/public/app/config/PageTwo.vue
lib/ui/public/app/config/components/Navigation.vue
lib/ui/public/app/fieldData.js
lib/ui/public/app/index.js
lib/ui/public/app/router.js
lib/ui/public/app/store.js
lib/ui/public/index.html
lib/ui/webpack.config.js
lib/ui/webpack.js
package.json
test/claim_spec.js
test/data_service_spec.js
test/helper_spec.js

Story details: https://app.clubhouse.io/active-prospect/story/12410

New: TrustedForm Data Service

---

.github/workflows/test.yml
README.md

> min node now 12 instead of 10
> Fix [#1](https://app.clubhouse.io/active-prospect/story/14213/update-integrations-to-node-12)

min node now 12 instead of 10

---

CHANGELOG.md
lib/claim.js
package.json
test/claim_spec.js

> Description here
> Link to Clubhouse Ticket Goes Here

use a custom reference rather than the standard field

---

lib/ui/index.js
package.json

Convert to integration-dev-dependencies 1.1.0
https://app.clubhouse.io/active-prospect/story/22082/update-webpack-config-in-dev-dependencies-packages

New dev deps

---

CHANGELOG.md
lib/claim.js
lib/helpers.js
test/claim_spec.js
test/helper_spec.js

fix reason on 500; support mobile certs
- https://app.shortcut.com/active-prospect/story/25816/lc-trustedform-integration-is-returning-a-different-error-when-encountering-a-500-system-error
- https://app.shortcut.com/active-prospect/story/30234/mobile-tf-certs-are-skipped-by-claim-integration

fix reason on 500; support mobile certs

---

CHANGELOG.md
lib/consent.js
test/consent_spec.js

fix reason for consent/plus_data
https://app.shortcut.com/active-prospect/story/33842/trustedform-consent-consent-data-return-incorrect-reason

fix reason for consent/plus_data

---

CHANGELOG.md
lib/claim.js
lib/consent.js
lib/data_service.js
lib/helpers.js
package.json
test/claim_spec.js
test/consent_spec.js
test/data_service_spec.js
test/helper_spec.js

add support for scan_delimiter
https://app.shortcut.com/active-prospect/story/34085/add-field-mapping-for-scan-delimiter-to-trustedform-integrations

add support for scan_delimiter

---

CHANGELOG.md
docs/outbound.data_service.md
docs/outbound.insights.md
index.js
lib/data_service.js
lib/insights.js
lib/ui/public/app/config/Page1.vue
lib/ui/public/app/config/Page2.vue
lib/ui/public/app/config/Page3.vue
test/claim_spec.js
test/consent_spec.js
test/data_service_spec.js
test/insights_spec.js

> Change "Data Service" language and variables to "Insights"
> https://app.shortcut.com/active-prospect/story/38895/rename-trustedform-data-service-to-trustedform-insights-integration

Sc 38895/rename trustedform data service to trustedform

---

lib/consent_plus_data.js
lib/insights.js

> Updated "Age" and "Age in Seconds" description for TF Inisights and TF Consent + Insights
> [Link to Shortcut/Jira Ticket Goes Here](https://app.shortcut.com/active-prospect/story/48650/incorrect-description-for-age-in-the-trustedform-enhancements)

Sc 48650/incorrect description for age in the trustedform

---

lib/ui/api/account.js
lib/ui/public/app/config/Page1.vue
lib/ui/public/app/config/Page2.vue
lib/ui/public/app/config/Page3.vue
lib/ui/public/app/config/Page4.vue
lib/ui/public/app/config/Page5.vue
lib/ui/public/app/store.js
package.json

A slew of styling updates. There are screenshots in [the ticket](https://app.shortcut.com/active-prospect/story/59650/trustedform-v4-improve-rich-ui-styling), here's a list of the updates made here
- The clickable space for the Product checkboxes to be increased; it should be 16 x 16 px
- Some padding to be added above Retain since it’s very close to the section above, and the only thing that's clickable is the very tiny checkbox
- The header should be fixed to the top when scrolling (in the TrustedForm Insights Configuration step)
- Update the main modal title to be Configure TrustedForm Insights (for the Insights step of the Rich UI)
- Update the internal modal title to be Select Insights Data Points instead of Select Data Points (for the Insights step of the Rich UI)
- Update …

Sc 59650/trustedform v4 improve rich UI styling

---

lib/ui/public/app/config/Page4.vue
lib/ui/public/app/store.js

1. When an account does not have access to any TrustedForm products, show an "error" type message telling the user to reach out to Support.
2. There's also a new "Loading products..." screen. This is required because otherwise there's no way to tell a difference between "loaded and no products available" vs "initial state, and no products available"
Here's a slow-mo version of the Loading screen (still quite fast)
https://github.com/activeprospect/leadconduit-integration-trustedform/assets/8379268/d631c518-29b4-4ad7-89d7-0be6d5a533f3
And here's the UX of the "no products available" window
https://github.com/activeprospect/leadconduit-integration-trustedform/assets/8379268/f5949e48-1263-409a-98a6-dee725163960
https://app.shortcut.com/active-prospect/story/67604/trustedform-v4-fix-add-on-ui- …

[Sc-67604] Add notice when account has no TF products available
