src/claim.coffee
As in #9, except kept the `[brackets]` and didn't add the ignore case flag `i`.
=> reduce regex to match hex only. fixes #9

package.json, spec/claim_spec.coffee, src/claim.coffee
This will set the integration outcome to `failure` if required scan text is missing or forbidden text is found. Current plan for message text is: 
> Required scan text not found in TrustedForm snapshot (missing 2: 'other disclosure text, some disclosure text')
The number of missing strings is given, followed by their alphabetically sorted and comma-separated strings. Because there may be many and/or long scan text strings, that part of the reason is truncated to 256 characters, in hopes that consumers of that data, e.g., Bad Reason Reports, would be kept more sane thereby.
=> Scan support

spec/claim_spec.coffee, src/claim.coffee
(i.e., what was scanned for). Fixes #10, again.
At your convenience, please, @alexkwolfe. :relaxed:
=> fixed to set the failure reason correctly based on request variables 

spec/claim_spec.coffee, src/claim.coffee
When a cert is captured with 'video', the age in seconds does not include the time the consumer spent filling out the form. 
https://github.com/activeprospect/trustedform/commit/40710d0#diff-87119a2a8497d0eeb372ebc03edb1628R21
=> Refine age in seconds to account for time spent on page

spec/claim_spec.coffee, src/claim.coffee
The latter is reserved for usage by the masking feature.
=> Use is_masked instead of masked

spec/claim_spec.coffee, src/claim.coffee
This change causes the integration to always pass arrays for scan terms to the TF claim API. It also guarantees that scan terms are not given more than once in the appended `found` and `not_found` arrays, and not given more than once in the failure reason.
=> Support scanning for multiple terms

CHANGELOG.md, lib/claim.js, lib/helpers.js, test/claim_spec.js
1) Adds response parsing for 404s returned by cert hashes. This change can probably be refactored out after the cert url changes land.
2) Adds `how_many_required_matched` property to appended data. The proposed name was `how_many_matched`, I added the `required` bit to clarify that the data contained is relevant _only_ to required texts. I'm not sure if that name is much better though, and it certainly doesn't roll of the tongue.
3) Moves helper functions into separate file. IMHO, this makes the code easier to read, especially after adding the `countRequiredScans` function. Happy to put them back if need be.
More info can be found in the second and third items [here.](https://activeprospect.tpondemand.com/entity/2570-trustedform-improvements)
=> Tf improvements

CHANGELOG.md, lib/claim.js, test/claim_spec.js
FB certs do not have geo data, which is causing the integration to bonk.
[TP Ticket](https://activeprospect.tpondemand.com/entity/3586-tf-integration-needs-work-it-is)
=> Guard against null geo data

CHANGELOG.md, lib/claim.js, package.json, test/claim_spec.js
This PR explicitly captures the `location` and `parent_location` data that is piped into the `url` property. `lodash` is also update to resolve security vulnerabilities.
CH ticket for [context](https://app.clubhouse.io/active-prospect/story/1862/trustedform-integration-provide-all-url-location-data)
=> Capture all url location data

.github/workflows/test.yml, .travis.yml, package.json
This is the basic replacement of Travis with GH Actions for integrations. I added codecov to the repo as well, but the token needs to be unique per repo.
=> Replace Travis with GH Actions

.gitignore, CHANGELOG.md, lib/claim.js, test/claim_spec.js
You can find more information [here](https://app.clubhouse.io/active-prospect/story/9290/allow-the-tf-integration-to-accept-http-certificate-urls).
I added some extra logic in the `handle` function to convert from http to https, but I'm open to different approaches too.
=> Added logic to change http to https. Small eslint fixes

CHANGELOG.md, lib/claim.js, package.json, test/claim_spec.js
Adds support for customizing `reference` in claim integration
https://app.clubhouse.io/active-prospect/story/20638/allow-for-customization-of-reference-value-through-new-mapping-on-outbound-delivery-step-in-lc
=> add support for customizing reference

CHANGELOG.md, lib/data_service.js, lib/ui/public/app/fieldData.js, test/data_service_spec.js
rename data_service 'masked' to 'is_masked' 
https://app.shortcut.com/active-prospect/story/32622/change-trustedform-data-service-integration-to-return-is-masked-instead-of-masked
=> rename data_service 'masked' to 'is_masked'

CHANGELOG.md, lib/consent.js, lib/consent_plus_data.js, test/consent_spec.js
Fixes issue found in QA. The `consent` integration _shouldn't_ ever get the `consent_plus_data` response, but if it somehow does, this fix prevents appending that extra `cert` data to the lead.
https://app.shortcut.com/active-prospect/story/32490/trustedform-consent-integration
=> fix to ensure consent ever appends cert data

CHANGELOG.md, lib/consent.js, test/consent_spec.js
use new boolean field names
https://app.shortcut.com/active-prospect/story/35791/update-trustedform-consent-consent-data-expected-boolean-response-properties
=> use new boolean field names

CHANGELOG.md, lib/data_service.js, test/data_service_spec.js
this change reduces the specificity of skip messages a little, but I think that's unavoidable for this change
https://app.shortcut.com/active-prospect/story/36477/allow-ping-urls-to-be-used-instead-of-cert-urls-in-trustedform-data-service
=> support ping urls in data service integration

CHANGELOG.md, lib/data_service.js, test/data_service_spec.js
allow TF staging ping URL
https://app.shortcut.com/active-prospect/story/37183/allow-a-trustedform-ping-url-to-be-passed-in-the-trustedfrom-cert-url-field-of-trustedform-data-service-integration
=> allow TF staging ping URL

CHANGELOG.md, lib/insights.js, test/insights_spec.js
> Remove response variable "billable" from insights.
> https://app.shortcut.com/active-prospect/story/47158/tf-insights-missing-from-usages-exclusion-list
=> Sc 47158/remove billiable response variable from insights

CHANGELOG.md, lib/insights.js, test/insights_spec.js
revert exclusion of TF insights from billable/usages (i.e., reverts to v2.0.0 functionality)
https://app.shortcut.com/active-prospect/story/47859/include-tf-insights-in-usages-results
=> revert exclusion of TF insights from billable/usages

lib/helpers.js, lib/trustedform.js, lib/ui/api/account.js, lib/ui/api/index.js, lib/ui/public/app/config/Page4.vue, lib/ui/public/app/store.js, lib/ui/public/app/v4fields.js, package.json, test/helper_spec.js, test/trustedform_spec.js
Added support for the Trustedform Verify function.
- When processing a Lead, the add-on will send the verify key along with the payload when validating the Trustedform certificate.
- A filter will be created and for any result with an outcome other than success, the flow will be stopped and a failure will be responded to the source.
> [Ticket SC-63442 TrustedForm v4 - Add Verify to Add-On](https://app.shortcut.com/active-prospect/story/63442/trustedform-v4-add-verify-to-add-on)
=> Sc 63442/trustedform v4 add verify to add on

lib/trustedform.js
This bug makes it impossible to use the 4.0 insights scan feature in this integration. 
Change the request variable types to `array`.
HOTFIX
=> Scan request variables should be typed as arrays

CHANGELOG.md, lib/claim.js, lib/consent.js, lib/trustedform.js, test/trustedform_spec.js
1. Fix insights vars check in case vars.insights is completely missing
2. Fix validations for Retain and Insights so they apply regardless of other products selected
https://app.shortcut.com/active-prospect/story/65226/trustedform-v4-insights-add-on-with-no-field-mappings-errors-in-validation
Tested locally. With this configuration
I got this result
=> Sc 65226/Handle missing Insights mappings in `validate`

CHANGELOG.md, lib/ui/public/app/config/Page5.vue, lib/ui/public/app/config/Page6.vue, lib/ui/public/app/index.js, lib/ui/public/app/router.js, lib/ui/public/app/store.js
1. If `PageScan` is selected, the user will be directed to a new page where they configure their required/forbidden page scan terms. I chose to make this page option (i.e. the user can "continue" without entering anything) because that's the way it currently works and I don't exactly see a problem with it, if someone wants to enable PageScan but not configure any terms. 🤷🏻 
There are screen recordings of the UX attached to the ticket
https://app.shortcut.com/active-prospect/story/65261/trustedform-v4-insights-add-on-ui-should-prompt-for-required-and-forbidden-scan-text
- [N/A]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code. (N/A because there are not Vue tests in this integration and it didn't feel like it was in …
=> [Sc 65261] Prompt user for PageScan terms when PageScan is selected

lib/ui/public/app/config/Page4.vue, lib/ui/public/app/config/Page6.vue
I botched a couple links. Also TIL that Chrome treats `mailto` links differently when `target="_blank"`.
https://app.shortcut.com/active-prospect/story/65261/trustedform-v4-insights-add-on-ui-should-prompt-for-required-and-forbidden-scan-text#activity-68580
https://app.shortcut.com/active-prospect/story/67604/trustedform-v4-fix-add-on-ui-to-handle-no-products#activity-68578
=> Fix external link: `target="_blank"`

CHANGELOG.md, lib/trustedform.js, test/trustedform_spec.js
adds `masked_cert_url` as a response variable for the v4 integration
https://app.shortcut.com/active-prospect/story/69416/trustedform-v4-0-add-on-not-appending-masked-certificate-url
=> add support for masked_cert_url

CHANGELOG.md, lib/trustedform.js, test/trustedform_spec.js
adds an optional API key mapping to the v4 integration
https://app.shortcut.com/active-prospect/story/69418/trustedform-v4-add-support-for-api-key-mapping
=> add custom api key support to v4 integration

CHANGELOG.md, lib/trustedform.js, package.json, test/trustedform_spec.js
updated v4 integration response to append language approved and ensure it is a boolean value
https://app.shortcut.com/active-prospect/story/74533/trustedform-v4-verify-language-approved-is-not-being-appended
=> Sc 74533/trustedform v4 verify language approved 

lib/trustedform.js, package.json, test/trustedform_spec.js
Fix verify response vars mapping
[Ticket](https://app.shortcut.com/active-prospect/story/78630/trustedform-verify-integration-is-not-appending-verify-responses-parameter-correctly)
=> Sc 78630/trustedform verify integration is not appending

lib/trustedform.js, lib/ui/public/app/config/Page1.vue, lib/ui/public/app/config/Page4.vue, lib/ui/public/app/config/Page5.vue, lib/ui/public/app/config/Page6.vue, lib/ui/public/app/config/Page7.vue, lib/ui/public/app/router.js, lib/ui/public/app/store.js, test/trustedform_spec.js
Adding 1:1 Consent Check Advertiser Name configuration and One To One Filter
[Ticket](https://app.shortcut.com/active-prospect/story/77184/trustedform-v4-verify-add-1-1-consent-check-feature)
=> Sc 77184/trustedform v4 verify add 1 1 consent check

CHANGELOG.md, lib/trustedform.js, test/trustedform_spec.js
fix v4 to append share_url
https://app.shortcut.com/active-prospect/story/84484/trustedform-v4-retain-include-trustedform-share-url-as-an-appended-field
=> fix v4 to append share_url

lib/ui/public/app/store.js
Fixing the issue with Trustedform rich UI reopening where the configured products aren't initializing as selected
https://app.shortcut.com/active-prospect/story/86334/implement-edit-step-for-trustedform-add-on
=> Retrieving the current products configs when re-opening the Rich UI

lib/trustedform.js, lib/ui/public/app/v4fields.js, test/trustedform_spec.js
- Add Verify `min_font_size_px_satisfied` and `min_contrast_ratio_satisfied` to appended data
- Add Insights `bot_detected`
Although they’re two separate tickets, both should be delivered together.
https://app.shortcut.com/active-prospect/story/88181/trustedform-v4-verify-include-min-font-size-px-satisfied-and-min-contrast-ratio-satisfied-as-an-appended-field
https://app.shortcut.com/active-prospect/story/88247/trustedform-v4-insights-include-bot-detected-property
=> Sc 88181/trustedform v4 verify include min font size

CHANGELOG.md, lib/trustedform.js, lib/ui/api/account.js, test/trustedform_spec.js
Because the `Authorization` header is already in use, I opted to stick the token in a custom header
https://app.shortcut.com/active-prospect/story/87918/send-cpl-data-to-trustedform
=> add support for cpl-token and update changelog

CHANGELOG.md, lib/trustedform.js, package.json, test/trustedform_spec.js
add support for verify.opt_in_types_satisfied
https://app.shortcut.com/active-prospect/story/90678/trustedform-v4-verify-include-opt-in-types-satisfied-as-an-appended-field
=> add support for verify.opt_in_types_satisfied
